@startuml note
Alice->Bob : hello
hnote left of Alice #aqua: this is a first note
Bob->Alice : ok
rnote right of Bob #green: this is another note
Bob->Bob : I am thinking
note left
a note
can also be defined
on several lines
end note
@enduml