@startuml signup
actor User
participant System

autonumber
User -> System: Requests login page
System -> User: Sends login page
autonumber 10
User -> System: Submits login credentials (username, password)
autonumber 20
System -> System: Verifies credentials

alt#Gold #Green Credentials are valid
    System -> User: Sends success message
else #Pink Credentials are invalid
autonumber 27 "<font color=red><b>Error Message"
    System -> User: Sends error message
end

@enduml