@startuml methods
Object <|-- ArrayList
Object : equals()
ArrayList : Object[] elementData
ArrayList : size()

class Dummy {
-String data
#void methods()
+equals()
}
class Flight {
+flightNumber : Integer
+departureTime : Date
-size()
~Object[] elementData
}

' Dummy : equals()
' Flight : Object[] elementData
' Flight : size()
@enduml